name: Build IP lists

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE*"
      - "*.md"
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Download CSV
      run: |
        curl -L "https://ipinfo.io/data/ipinfo_lite.csv.gz?_src=frontend&token=${{ secrets.IPINFO_TOKEN }}" -o ipinfo_lite.csv.gz

    - name: Generate country lists
      run: |
        mkdir -p geo/geoip
        python scripts/parse.py

    - name: Install mihomo
      run: |
        M_VER=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | \
                grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        echo "Latest mihomo version: $M_VER"
        wget -O mihomo.gz https://github.com/MetaCubeX/mihomo/releases/download/v${M_VER}/mihomo-linux-amd64-v${M_VER}.gz
        gunzip -f mihomo.gz
        chmod +x mihomo
        sudo mv mihomo /usr/local/bin/
        mihomo -v

    - name: Convert .lst to .mrs
      run: |
        for file in geo/geoip/*.lst; do
          mihomo convert-ruleset ipcidr text "$file" "${file%.lst}.mrs"
        done

    - name: Commit and push generated files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "IP List Generator"
        git config user.email "noreply@myrepo.com"
        git add geo/geoip/
        git commit -m "Update country IP lists" || echo "No changes"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
